user_name: "app"
user_uid: 1000
user_home: "/home/{{ user_name }}"
backend_database_user: "aalto_user"
backend_database_name: "aalto_backend"
backend_database_password: "{{ lookup('ansible.builtin.password', '/dev/null length=24') }}"
