- name: Create docker-compose directory
  ansible.builtin.file:
    path: /root/grafana
    state: directory
    mode: "0755"

- name: Create mount root folder directory
  ansible.builtin.file:
    path: /var/lib/grafana
    state: directory
    mode: "0750"

- name: Check if docker-compose.yml already exists
  ansible.builtin.stat:
    path: /root/grafana/docker-compose.yml
  register: stat_docker_compose

- name: Tear down existing container(s)
  community.docker.docker_compose:
    project_src: /root/grafana
    state: absent
  when: stat_docker_compose.stat.exists
  register: teardown
  failed_when: not teardown.changed

- name: Copy template file to remote
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /root/grafana/docker-compose.yml
    owner: root
    group: root
    mode: "0644"

- name: Copy Grafana config
  ansible.builtin.template:
    src: grafana.ini.j2
    dest: /etc/grafana.ini
    mode: "640"
    backup: true

- name: Run docker compose to create Grafana container
  community.docker.docker_compose:
    project_src: /root/grafana
  register: output

- name: Show docker container information
  ansible.builtin.debug:
    var: output

- name: Run docker compose again
  community.docker.docker_compose:
    project_src: /root/grafana
    build: false
  register: output

- name: Check that app is up
  ansible.builtin.assert:
    that: not output.changed

- name: Verify Grafana is up and running
  ansible.builtin.uri:
    url: http://localhost:3000
