---
# This playbook deploys the whole stack for the aalto-2022 project.
- hosts: all
  remote_user: root
  roles:
    - common
    - app
    - proxy

# Add Nginx + logrotate
- hosts: server1
  remote_user: root
  roles:
    - web
    - grafana
