---
# This playbook deploys the whole stack for the aalto-2022 project.
- hosts: all
  remote_user: root
  roles:
    - common
    - app
    - proxy

# Add web services
- hosts: server1
  remote_user: root
  vars:
    certbot_create_method: standalone
  roles:
    - role: geerlingguy.certbot
      tags: certbot
    - role: web
      tags: web
    - role: loki
      tags: loki
    - role: grafana
      tags: grafana
