- name: Install backend systemd unit file
  ansible.builtin.template:
    src: service.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"
    owner: root
    group: root
    mode: "0644"
  notify: "Reload systemd"
