- name: Copy frontend static files to nginx
  ansible.builtin.copy:
    src: "{{ app_dir }}/deploy/public/"
    dest: /srv/http
    owner: root
    group: root
    mode: "0755"
    remote_src: true

- name: Copy backend files to live folder
  ansible.builtin.copy:
    src: "{{ app_dir }}/deploy/"
    dest: "{{ live_dir }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0750"
    remote_src: true

- name: Install backend systemd unit file
  ansible.builtin.template:
    src: service.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"

- name: Start backend service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: started
    enabled: true
    daemon_reload: true

- name: Check if backend service is running
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: started
    enabled: true
  check_mode: true
  register: service
  failed_when: (service is changed) or (service is failed)

- name: Verify backend is up and running
  ansible.builtin.uri:
    url: http://localhost:3030
