- name: Make sure app live folder exists
  ansible.builtin.file:
    path: "{{ live_dir }}"
    state: directory
    mode: "0755"

- name: Check if backend files exist
  ansible.builtin.stat:
    path: "{{ live_dir }}/index.js"
  register: indexjs

- name: Copy dummy index.js when it does not exist
  ansible.builtin.copy:
    src: index.js
    dest: "{{ live_dir }}"
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0755"
  when: not indexjs.stat.exists

- name: Install backend systemd unit file
  ansible.builtin.template:
    src: service.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"
    owner: root
    group: root
    mode: "0644"

- name: Start backend service
  ansible.builtin.systemd:
    name: "{{ service_name }}"
    state: started
    enabled: true
    daemon_reload: true

- name: Check if backend service is running
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: started
    enabled: true
  check_mode: true
  register: service
  failed_when: (service is changed) or (service is failed)

- name: Verify backend is up and running
  ansible.builtin.uri:
    url: http://localhost:3030
