---
- name: Install common dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - acl
    - sudo
    - docker-compose
    - docker.io
    - ufw
  tags: deps

- name: Add the app user
  ansible.builtin.user:
    name: "{{ user_name }}"
    uid: "{{ user_uid }}"
    home: "{{ user_home }}"
    shell: /bin/bash

- name: Set up firewall with UFW
  ansible.builtin.import_tasks: ufw.yml
  tags: firewall
