---
- name: Install common dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - sudo
    - acl
    - docker.io
    - docker-compose
  tags:
    deps

- name: Add the app user
  ansible.builtin.user:
    name: "{{ user_name }}"
    uid: "{{ user_uid }}"
    home: "{{ user_home }}"
    shell: /bin/bash
