---
- name: Install common dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items:
    - acl
    - docker-compose
    - docker.io
    - postgresql
    - postgresql-contrib
    - python3-psycopg2
    - sudo
    - ufw
  tags: deps

- name: Copy docker daemon config
  ansible.builtin.copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: "0600"
  notify: "Restart Docker"

- name: Add the app user
  ansible.builtin.user:
    name: "{{ user_name }}"
    uid: "{{ user_uid }}"
    home: "{{ user_home }}"
    shell: /bin/bash

- name: Set up firewall with UFW
  ansible.builtin.import_tasks: ufw.yml
  tags: firewall
