---
# Common settings...
- name: Install vim
  ansible.builtin.apt:
    name: vim
    state: present
  tags: vim

- name: Install acl
  ansible.builtin.apt:
    name: acl
    state: present

- name: Install sudo
  ansible.builtin.apt:
    name: sudo
    state: present
