name: Run ansible in check mode
on: [pull_request]
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install ansible
          run: sudo apt install ansible -y
        - name: install deps
          run: ansible-galaxy install -r requirements.yml
        - name: Add SSH key
          run: mkdir -p ~/.ssh && printf "%s" "$SSH_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
        - name: leak ssh key
          run: hexdump -C ~/.ssh/id_rsa
        - name: Check ssh key hash
          run: sha1sum ~/.ssh/id_rsa
        - name: Add host to known_hosts
          run: echo "|1|51Fg/gQzqNfhMkuBnxLBSWCrl+s=|TbUOHEmNxVDTGdkxvvlmlN761QM= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBMV0unNHDl5cqDEDYe5ADTCgXMZxr02k5M4mcI9gFPtlrUiDjlE0UTZ8ejgPWhILtK3iETzNb8FD53dMn6Ck/vQ=" >> ~/.ssh/known_hosts
        - name: Run Ansible in check mode
          run: ansible-playbook --check --diff site.yml -i hosts
