name: Run ansible in check mode
on: [pull_request]
jobs:
    check:
        runs-on: ubuntu-latest
        - uses: actions/checkout@v2
        - name: Install ansible
          run: apt install ansible -y
        - name: install deps
          run: ansible-galaxy install -r requirements.yml
        - name: Add SSH key
          run: echo $SSH_KEY > .ssh/id_rsa
        - name: Run Ansible in check mode
          run: ansible-playbook --check --diff site.yml -i hosts
